node_lines:
- node_line_name: retrieve_node_line
  nodes:
    - node_type: retrieval
      strategy:
        metrics: [retrieval_f1, retrieval_recall, retrieval_precision,
                  retrieval_map, retrieval_mrr, retrieval_ndcg]
      top_k: [5, 10, 20, 30]
      modules:
        - module_type: vectordb
          embedding_model:
            - mxbai-embed-xsmall-v1