node_lines:
- node_line_name: retrieve_node_line
  nodes:
    - node_type: retrieval
      strategy:
        metrics: [retrieval_f1, retrieval_recall, retrieval_precision,
                  retrieval_map, retrieval_mrr, retrieval_ndcg]
      top_k: [5, 10, 20, 30, 50, 100]
      modules:
        - module_type: vectordb
          embedding_model:
            # - mxbai-embed-large-v1
            # - bge-m3
            # - qwen3-embedding-0.6b
            # - inf-retriever-v1-1.5b
            # - gte-qwen2-1.5b-instruct
            # - amazon-titan-embed-text-v2
            # - cohere-embed-multilingual-v3
            # - text-multilingual-embedding-002
            - gemini-embedding-001